version: '3'

services:
  sql-benchmark:
    build: ./postgresql
    volumes:
      - ./postgresql:/app
    ports:
      - 5000:5000
    depends_on:
      - nosql-benchmark
  nosql-benchmark:
    build: ./mongodb
    volumes:
      - ./mongodb:/app
    ports:
      - 5001:5001
